# Generated by Django 5.2 on 2026-01-11 15:24

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_settings_pgvector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'groups',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('admin', 'Admin'), ('supervisor', 'Supervisor'), ('user', 'User')], max_length=255)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField()),
                ('face_vector', pgvector.django.vector.VectorField(dimensions=512)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='AttendanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('remaining_amount', models.IntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.group')),
            ],
            options={
                'db_table': 'attendance_types',
            },
        ),
        migrations.CreateModel(
            name='InvitationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled ', 'Cancelled')], max_length=255)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.group')),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='invitee_set', to='app.user')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='inviter_set', to='app.user')),
            ],
            options={
                'db_table': 'invitation_requests',
            },
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date_time', models.DateTimeField()),
                ('end_date_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled ', 'Cancelled')], max_length=255)),
                ('reason', models.TextField()),
                ('attendance_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.attendancetype')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.group')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='supervisor_set', to='app.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='user_set', to='app.user')),
            ],
            options={
                'db_table': 'approval_requests',
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.group')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.user')),
            ],
            options={
                'db_table': 'user_groups',
            },
        ),
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date_time', models.DateTimeField()),
                ('end_date_time', models.DateTimeField()),
                ('attendance_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.attendancetype')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.user')),
            ],
            options={
                'db_table': 'user_logs',
            },
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=255)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_all_day', models.BooleanField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.group')),
            ],
            options={
                'db_table': 'working_hours',
            },
        ),
    ]
