# Generated by Django 5.2 on 2026-04-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlog',
            name='type',
            field=models.CharField(choices=[('clock_in', 'Clock In'), ('clock_out', 'Clock Out'), ('late', 'late')], default='unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('admin', 'Admin'), ('supervisor', 'Supervisor'), ('user', 'Member')], max_length=255),
        ),
    ]
