# Generated by Django 5.2 on 2026-04-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_userlog_type_alter_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='type',
            field=models.CharField(choices=[('clock_in', 'Clock In'), ('clock_out', 'Clock Out'), ('late', 'late'), ('leave', 'leave'), ('override', 'override')], max_length=255),
        ),
    ]
