# Generated by Django 5.2 on 2026-05-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_userlog_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='type',
            field=models.CharField(choices=[('clock_in', 'Clock In'), ('clock_out', 'Clock Out'), ('late', 'Late'), ('leave', 'Leave'), ('override', 'Override')], max_length=255),
        ),
    ]
