# Generated by Django 5.2 on 2026-05-01 17:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_invitationrequest_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationrequest',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='invitationrequest',
            name='status_updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
