# Generated by Django 5.2 on 2026-05-02 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_invitationrequest_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workinghours',
            name='is_all_day',
        ),
    ]
