# Generated by Django 5.2 on 2026-05-02 08:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_invitationrequest_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitationrequest',
            name='status_updated_at',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='overriderequest',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
