# Generated by Django 5.2 on 2026-05-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_invitationrequest_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='type',
            field=models.CharField(choices=[('late', 'Late'), ('leave', 'Leave'), ('override', 'Override')], max_length=255),
        ),
    ]
