# Generated by Django 5.2 on 2026-05-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_user_password_alter_userlog_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='type',
            field=models.CharField(choices=[('late', 'Late'), ('leave', 'Leave'), ('override', 'Override')], max_length=255, null=True),
        ),
    ]
