# Generated by Django 5.2 on 2026-05-03 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_userlog_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overriderequest',
            name='end_date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='overriderequest',
            name='start_date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='attendance_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='app.attendancetype'),
        ),
    ]
