# Generated by Django 5.2 on 2026-05-08 15:31

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_overriderequest_end_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlog',
            name='reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='face_vector',
            field=pgvector.django.vector.VectorField(dimensions=512, null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='end_date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='start_date_time',
            field=models.DateTimeField(null=True),
        ),
    ]
