# Generated by Django 5.2 on 2026-05-21 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_userlog_reason_alter_user_face_vector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='type',
            field=models.CharField(choices=[('late', 'Late'), ('leave', 'Leave'), ('override (clock in)', 'Override Clock In'), ('override (clock out)', 'Override Clock Out'), ('override (clock in and out)', 'Override Clock In and Out')], max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name='leaveremaining',
            table='leave_remainings',
        ),
    ]
