# Generated by Django 5.2 on 2026-05-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_userlog_type_alter_leaveremaining_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='type',
            field=models.CharField(choices=[('late', 'Late'), ('leave', 'Leave'), ('override clock in', 'Override Clock In'), ('override clock out', 'Override Clock Out'), ('override clock in and out', 'Override Clock In and Out')], max_length=255, null=True),
        ),
    ]
