# Generated by Django 5.2 on 2026-05-31 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_userlog_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancetype',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
