# Generated by Django 5.2 on 2026-05-31 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_attendancetype_is_deleted'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendancetype',
            index=models.Index(fields=['group'], name='attendance__group_i_dfb7c9_idx'),
        ),
        migrations.AddIndex(
            model_name='invitationrequest',
            index=models.Index(fields=['invitee', 'inviter', 'group'], name='invitation__invitee_f3bc41_idx'),
        ),
        migrations.AddIndex(
            model_name='leaveremaining',
            index=models.Index(fields=['user', 'group', 'attendance_type'], name='leave_remai_user_id_377172_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['user', 'group', 'supervisor', 'attendance_type'], name='leave_reque_user_id_43d88a_idx'),
        ),
        migrations.AddIndex(
            model_name='overriderequest',
            index=models.Index(fields=['user', 'group', 'supervisor'], name='override_re_user_id_5a8da4_idx'),
        ),
        migrations.AddIndex(
            model_name='usergroup',
            index=models.Index(fields=['user', 'group', 'role'], name='user_groups_user_id_ab7e13_idx'),
        ),
        migrations.AddIndex(
            model_name='userlog',
            index=models.Index(fields=['user', 'group', 'attendance_type'], name='user_logs_user_id_8a9075_idx'),
        ),
        migrations.AddIndex(
            model_name='workinghours',
            index=models.Index(fields=['group'], name='working_hou_group_i_b503e3_idx'),
        ),
    ]
