# Generated by Django 5.2 on 2026-06-01 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_attendancetype_attendance__group_i_dfb7c9_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancetype',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.group'),
        ),
        migrations.AlterField(
            model_name='invitationrequest',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.group'),
        ),
        migrations.AlterField(
            model_name='invitationrequest',
            name='invitee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='invitee_set', to='app.user'),
        ),
        migrations.AlterField(
            model_name='invitationrequest',
            name='inviter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='inviter_set', to='app.user'),
        ),
        migrations.AlterField(
            model_name='leaveremaining',
            name='attendance_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.attendancetype'),
        ),
        migrations.AlterField(
            model_name='leaveremaining',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.group'),
        ),
        migrations.AlterField(
            model_name='leaveremaining',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.user'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='attendance_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.attendancetype'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.group'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='supervisor_leave_set', to='app.user'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_leave_set', to='app.user'),
        ),
        migrations.AlterField(
            model_name='overriderequest',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.group'),
        ),
        migrations.AlterField(
            model_name='overriderequest',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='supervisor_override_set', to='app.user'),
        ),
        migrations.AlterField(
            model_name='overriderequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_override_set', to='app.user'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.group'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.role'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.user'),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='attendance_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.attendancetype'),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.group'),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.user'),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.group'),
        ),
    ]
