# Generated by Django 5.2 on 2026-06-01 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_attendancetype_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancetype',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.group'),
        ),
        migrations.AlterField(
            model_name='invitationrequest',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.group'),
        ),
        migrations.AlterField(
            model_name='leaveremaining',
            name='attendance_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.attendancetype'),
        ),
        migrations.AlterField(
            model_name='leaveremaining',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.group'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='attendance_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.attendancetype'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.group'),
        ),
        migrations.AlterField(
            model_name='overriderequest',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.group'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.group'),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='attendance_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.attendancetype'),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.group'),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.group'),
        ),
    ]
