# Generated by Django 5.2 on 2025-11-16 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField()),
                ('photo', models.FilePathField(path='assets')),
            ],
        ),
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ONGOING', 'On Going'), ('DONE', 'Done')])),
            ],
        ),
        migrations.CreateModel(
            name='VotingCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='restapi.user')),
                ('voting_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='restapi.voting')),
            ],
        ),
        migrations.CreateModel(
            name='VotingChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='candidate_id', to='restapi.user')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='user_id', to='restapi.user')),
                ('voting_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='restapi.voting')),
            ],
        ),
        migrations.CreateModel(
            name='VotingParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='restapi.user')),
                ('voting_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='restapi.voting')),
            ],
        ),
    ]
