# Generated by Django 5.2 on 2025-11-16 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votingchoice',
            name='candidate_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='candidate_set', to='restapi.user'),
        ),
        migrations.AlterField(
            model_name='votingchoice',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='user_set', to='restapi.user'),
        ),
    ]
