# Generated by Django 5.2 on 2025-11-16 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_alter_votingchoice_candidate_id_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
        migrations.AlterModelTable(
            name='voting',
            table='votings',
        ),
        migrations.AlterModelTable(
            name='votingcandidate',
            table='voting_candidates',
        ),
        migrations.AlterModelTable(
            name='votingchoice',
            table='voting_choices',
        ),
        migrations.AlterModelTable(
            name='votingparticipant',
            table='voting_participants',
        ),
    ]
