# Generated by Django 5.2 on 2025-11-16 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_alter_user_table_alter_voting_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.FilePathField(path='SecureVoteBE/restapi/assets'),
        ),
    ]
