# Generated by Django 5.2.8 on 2025-12-01 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0004_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.FilePathField(path='SecureVoteBE/restapi/assets/'),
        ),
    ]
