# Generated by Django 5.2.8 on 2025-12-13 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0005_alter_user_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votingcandidate',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='votingcandidate',
            old_name='voting_id',
            new_name='voting',
        ),
        migrations.RenameField(
            model_name='votingchoice',
            old_name='candidate_id',
            new_name='candidate',
        ),
        migrations.RenameField(
            model_name='votingchoice',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='votingchoice',
            old_name='voting_id',
            new_name='voting',
        ),
        migrations.RenameField(
            model_name='votingparticipant',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='votingparticipant',
            old_name='voting_id',
            new_name='voting',
        ),
    ]
